### ISSUE TITLE
[mqtt-benchmark command] Error when run mqtt-benchmark

### ISSUE THREAD

**Issue by VienArchway** [hareeqi/mqtt-benchmark#1]
Hi @hareeqi 

**Context**

I want to install mqtt-benchmark to execute MQTT test case
Install link: https://www.npmjs.com/package/mqtt-benchmark

**Problem**
- I executed command `mqtt-benchmark` or `mqtt-benchmark --broker=mqtt://<myhost>:<myport>`

It has an error occurred 
```
C:\Users\phamthevien\AppData\Roaming\npm\node_modules\mqtt-benchmark\index.js:40
const publish = async (c ) =>{
                      ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\phamthevien\AppData\Roaming\npm\node_modules\mqtt-benchmark\bin\mqtt-benchmark:3:1)
```
**Solution**
- npm uninstall or reinstall but have same error.
Still not resolve this problem.

**Comment by swinterberger** [comment]
While this is old, it isnt an issue with the repo.  Your version of nodejs does not support async, you need to update.

**Comment by hareeqi** [comment]
hello @VienArchway , as @swinterberger said you are using an old node version. async support started in node v7.6 and higher.

I am gonna close the issue.
